version: 'ci-build-{build}'

pull_requests:
  do_not_increment_build_number: true

image:
- Visual Studio 2017
- Ubuntu

cache:
  - '%USERPROFILE%\.nuget\packages -> **\*.csproj'
  - '/home/appveyor/.nuget/packages -> **/*.csproj'

nuget:
  disable_publish_on_pr: true

configuration: Debug
build_script:
- pwsh: ./build.ps1 -Configuration $env:CONFIGURATION -BuildNumber $env:APPVEYOR_BUILD_NUMBER -CI
test_script:
- pwsh: ./test.ps1 -Configuration $env:CONFIGURATION

branches:
  except:
  - /^release\/.*$/

artifacts:
  - path: '**/*.*nupkg'
    name: NuGet Packages

deploy:
  provider: NuGet
  name: MyGet
  on:
    branch: dev
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
  server: https://www.myget.org/F/appcorenet/api/v2/package
  api_key:
    secure: eB0zjsEqa4oBKHhgwqhd62CdOG5YIKyTHEApHF9xwxuxjplKdIKBYEn2R2/6ITOb
  artifact: /.*\.nupkg/
